### ISSUE TITLE
[BUG] My map doesn't load, just blank.

### ISSUE THREAD

**Issue by MatheusMoreira0101** [localeai/covid19-live-visualization#12]
My map doesn't load, just blank.
![image](https://user-images.githubusercontent.com/54282051/80834683-9010e300-8bc7-11ea-95db-0f200a8dbf18.png)

**Comment by haxzie** [comment]
Hey @MatheusMoreira0101 Are you running the project locally?
Please provide me with more infor regarding the following.
- Your browser and it's version
- Operating System you are working one

**Comment by MatheusMoreira0101** [comment]
yes, it's running locally
chrome version 81.0.4044.138
firefox version 75.0
Operating System Windows 10

**Comment by haxzie** [comment]
Please double check your .env file for missing MapBox API tokens and please check the console.logs if you can find any issues logged.

**Comment by MatheusMoreira0101** [comment]
![image](https://user-images.githubusercontent.com/54282051/82288065-0a878400-9978-11ea-95e7-0024fb0207de.png)
I managed to solve more I had to add my style in the file DeckGL.vue in line 43, because I was using my token with his style and it was not working, the map appears the layers too, but the api data about the covid numbers does not are updated

**Comment by MatheusMoreira0101** [comment]
![image](https://user-images.githubusercontent.com/54282051/82288170-4a4e6b80-9978-11ea-91f1-6bedff1bad1f.png)
Essa imagem é usando o estilo padrao que veio no code!

**Comment by MatheusMoreira0101** [comment]
O que posso fazer pra conseguir atualizar as resposata do api do covid ?

**Comment by haxzie** [comment]
Hey @MatheusMoreira0101 the data for the app is generated using this https://github.com/haxzie/covid19-layers-api . You can fork this repo and update the data by running `npm start` and pushing the generated data back to your fork. You might also need to update the env in the app to point to your fork to collect the data.
