### ISSUE TITLE
Remove/replace deprecated npm request library

### ISSUE THREAD

**Issue by Committing** [localeai/covid19-live-visualization#5]
![Image of Yaktocat](https://i.gyazo.com/4be0720aad1e7bcfd157363869002a32.png)

https://github.com/request/request/issues/3142

**Comment by haxzie** [comment]
Thanks for reporting @Committing :raised_hands:

**Comment by nainardev** [comment]
Try node-fetch

**Comment by haxzie** [comment]
`request` is not a direct dependency on the project. There's not much we can do unless the maintainers of these packages update them.

https://github.com/nodejs/node-gyp/issues/2047

```
+-- @vue/cli-plugin-babel@4.2.3
| `-- @vue/cli-shared-utils@4.2.3
|   `-- request@2.88.2  deduped
`-- node-sass@4.13.1
  +-- node-gyp@3.8.0
  | `-- request@2.88.2  deduped
  `-- request@2.88.2 
```
